theme: jekyll-theme-Tactile
author: Attila Kovacs
github_username: attipaci
description: SuperNOVAS C/C++ astrometry library
show_downloads: false
google_analytics: G-HLFWKSM8V9
url: "https://smithsonian.github.io"
read_time: true
plugins:
  - jekyll-sitemap

