theme: jekyll-theme-Tactile
author: Attila Kovacs
github_username: attipaci
title: SuperNOVAS
description: The NOVAS C library, made better
show_downloads: false
google_analytics: G-HLFWKSM8V9
url: "https://smithsonian.github.io"
read_time: true
plugins:
  - jekyll-sitemap

