theme: jekyll-theme-Tactile
author: Attila Kovacs
github_username: attipaci
title: SuperNOVAS
description: SuperNOVAS C/C++ astrometry library
show_downloads: false
google_analytics: G-HLFWKSM8V9
url: "https://smithsonian.github.io"
read_time: true
titles_from_headings:
  strip_title: true
toc:
  min_level: 2
  max_level: 2
plugins:
  - jekyll-sitemap
  - jekyll-titles-from-headings
  - jekyll-toc

