theme: jekyll-theme-Tactile
author: Attila Kovacs
title: SuperNOVAS
description: The NOVAS C library, made better
show_downloads: false
google_analytics: G-HLFWKSM8V9
url: "https://smithsonian.github.io"
plugins:
  - jekyll-sitemap

